apiVersion: config.openshift.io/v1
kind: ImageDigestMirrorSet
metadata:
    name: external-secrets
spec:
    imageDigestMirrors:
        - mirrors:
            - esotest.azurecr.io/external-secrets-helm-operator
          source: ghcr.io/external-secrets/external-secrets-helm-operator
          mirrorSourcePolicy: NeverContactSource
        - mirrors:
            - esotest.azurecr.io/external-secrets
          source: ghcr.io/external-secrets/external-secrets
          mirrorSourcePolicy: NeverContactSource
